package com.devicelk.inventory.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity representing a single product held in the DeviceLK inventory.
 * <p>
 * This is the <b>Domain/Model</b> layer. The class is mapped to the
 * {@code products} table; Hibernate generates the schema automatically
 * (see {@code spring.jpa.hibernate.ddl-auto}).
 * <p>
 * Holds catalogue facts only. On-hand quantities live on {@code Stock}
 * ({@code inventory.stock}, keyed by product id) so that stock movements — a
 * high-churn, separately-versioned concern — never contend with edits to the
 * product record itself.
 */
@Entity
@Table(
        name = "products",
        schema = "inventory",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uc_product_name_brand",
                        columnNames = {"name", "brand"}
                )
        }
)
public class Product {

    /** ISO-4217 code applied when a caller does not specify one. */
    public static final String DEFAULT_CURRENCY = "LKR";

    /** Surrogate primary key, generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Product name is required")
    @Column(nullable = false)
    private String name;

    @NotBlank(message = "Brand is required")
    @Column(nullable = false)
    private String brand;

    /**
     * Stored as its {@code String} name (e.g. "LAPTOP") rather than its ordinal,
     * keeping the column human-readable and resilient to enum reordering.
     */
    @NotNull(message = "Category is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private Category category;

    /**
     * Price in minor units (cents), never a decimal type: integer arithmetic
     * removes any chance of a floating-point rounding artefact reaching a
     * customer-visible total. Rendered for transport via
     * {@link Money#toDisplayString(long)} — the single conversion point.
     * <p>
     * Declared {@code long} rather than {@code Long} so the column can never be
     * left null; {@code @Positive} rejects both a missing value (which binds to
     * 0) and an explicit non-positive one.
     */
    @Positive(message = "Price must be greater than zero")
    @Column(name = "price_cents", nullable = false)
    private long priceCents;

    /**
     * ISO-4217 code for {@link #priceCents}. Single-currency today, but the
     * amount is meaningless without it, so the unit travels with the number
     * rather than being assumed by each reader.
     */
    @NotBlank(message = "Currency is required")
    @Size(min = 3, max = 3, message = "Currency must be a 3-letter ISO-4217 code")
    @Column(nullable = false, length = 3, columnDefinition = "char(3)")
    // CHAR, not the VARCHAR Hibernate assumes for a String. Without this, the
    // columnDefinition above builds a bpchar column that schema validation then
    // rejects as the wrong type — DDL generation reads columnDefinition, while
    // validation compares against the mapped JDBC type, and the two disagreed.
    // Declaring the type here makes them agree on the fixed-width column that was
    // intended: an ISO-4217 code is always exactly three characters.
    @JdbcTypeCode(SqlTypes.CHAR)
    private String currency = DEFAULT_CURRENCY;

    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    @Column(length = 1000)
    private String description;

    /** No-args constructor required by JPA. */
    public Product() {
    }

    /** Convenience constructor for creating a new (unpersisted) product. */
    public Product(String name,
                   String brand,
                   Category category,
                   long priceCents,
                   String currency,
                   String description) {
        this.name = name;
        this.brand = brand;
        this.category = category;
        this.priceCents = priceCents;
        this.currency = currency;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public long getPriceCents() {
        return priceCents;
    }

    public void setPriceCents(long priceCents) {
        this.priceCents = priceCents;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
