package com.devicelk.order.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.Check;

import java.util.UUID;

/**
 * One line of an {@link Order}: what was bought, how many, and at what price.
 * Mapped to {@code orders.order_items}.
 * <p>
 * <b>Everything here is a snapshot, and that is the entire point of the table.</b>
 * A cart line can afford to hold only a {@code productId} and resolve the rest
 * from inventory on every read, because a cart describes a present intention. An
 * order describes a past event, and the answer to "what did I buy in March" must
 * not change because the catalogue was edited in April. So {@link #productName}
 * is copied in at checkout and never refreshed: if the product is later renamed,
 * re-priced, or deleted outright, this row still says what the customer actually
 * ordered. Resolving the name live would make order history quietly rewrite
 * itself, and — for a deleted product — fail to render at all.
 * <p>
 * <b>Product reference is by value, not by key.</b> {@link #productId} is a plain
 * {@code BIGINT} pointing at {@code inventory.products} with no foreign key across
 * the schema boundary, matching the rule the cart module follows. A cross-schema
 * FK would weld the modules together in the database and block the eventual split
 * into services; more concretely here, it would make deleting a product either
 * impossible or cascade into rewriting order history, which is the outcome this
 * table exists to prevent. The id is kept anyway — not to read the name from, but
 * so an order line can still be traced back to a catalogue entry that does exist.
 * <p>
 * The FK to the owning order, by contrast, <i>is</i> a real one: both tables live
 * in the {@code orders} schema, so it constrains nothing outside this module.
 */
@Entity
@Table(name = "order_items", schema = "orders")
// An ordered line of zero or fewer units is not a thing that happened. Enforced
// in the database so it holds against any writer, not only the ones that run
// Bean Validation first.
@Check(name = "ck_order_item_quantity_positive", constraints = "quantity > 0")
public class OrderItem {

    /** Surrogate key, generated by Hibernate rather than the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * The owning order. Lazy because the common traversal runs the other way —
     * loading an order and walking its lines — and an eager back-reference would
     * re-fetch the parent once per line.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "order_id",
            nullable = false,
            updatable = false,
            foreignKey = @jakarta.persistence.ForeignKey(name = "fk_order_items_order")
    )
    private Order order;

    /** Value reference to {@code inventory.products.id} — intentionally not a FK. */
    @NotNull(message = "Product id is required")
    @Column(name = "product_id", nullable = false, updatable = false)
    private Long productId;

    /**
     * The product's name as it stood when the order was placed.
     * <p>
     * Duplicated from inventory on purpose. This is the column that makes order
     * history survive a product being renamed or deleted — see the class note.
     */
    @NotBlank(message = "Product name is required")
    @Column(name = "product_name", nullable = false, updatable = false)
    private String productName;

    @Positive(message = "Quantity must be greater than zero")
    @Column(name = "quantity", nullable = false, updatable = false)
    private int quantity;

    /**
     * Unit price in minor units, as the customer was quoted it.
     * <p>
     * {@code PositiveOrZero} rather than {@code Positive}: a promotional or
     * bundled line can legitimately be free, and rejecting that here would be
     * this module inventing a pricing rule that is not its to make.
     */
    @PositiveOrZero(message = "Unit price cannot be negative")
    @Column(name = "unit_price_cents", nullable = false, updatable = false)
    private long unitPriceCents;

    /** ISO-4217 code for {@link #unitPriceCents}; the amount is unreadable without it. */
    @NotBlank(message = "Currency is required")
    @Size(min = 3, max = 3, message = "Currency must be a 3-letter ISO-4217 code")
    @Column(name = "currency", nullable = false, updatable = false, length = 3,
            columnDefinition = "char(3)")
    private String currency;

    /** No-args constructor required by JPA. */
    protected OrderItem() {
    }

    /**
     * Creates a line from the values checkout captured at the moment of purchase.
     * <p>
     * The order back-reference is set by {@link Order#addItem(OrderItem)}, not
     * here, so one place keeps both ends of the association consistent.
     */
    public OrderItem(Long productId,
                     String productName,
                     int quantity,
                     long unitPriceCents,
                     String currency) {
        this.productId = productId;
        this.productName = productName;
        this.quantity = quantity;
        this.unitPriceCents = unitPriceCents;
        this.currency = currency;
    }

    /**
     * Extended total for this line, in minor units.
     * <p>
     * Integer arithmetic throughout — the reason prices are stored as cents in
     * the first place.
     */
    public long lineTotalCents() {
        return unitPriceCents * quantity;
    }

    public UUID getId() {
        return id;
    }

    public Order getOrder() {
        return order;
    }

    /** Package-private: the association is managed by {@link Order}, not by callers. */
    void setOrder(Order order) {
        this.order = order;
    }

    public Long getProductId() {
        return productId;
    }

    public String getProductName() {
        return productName;
    }

    public int getQuantity() {
        return quantity;
    }

    public long getUnitPriceCents() {
        return unitPriceCents;
    }

    public String getCurrency() {
        return currency;
    }
}
