package com.devicelk.order.domain;

import com.devicelk.order.OrderStatus;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

/**
 * A placed order belonging to one user, mapped to {@code orders.orders}.
 * <p>
 * The aggregate root of the order module: {@link OrderItem}s have no life of
 * their own and are reached and added only through the order that owns them.
 * <p>
 * <b>An order is a record of something that happened, not a working document.</b>
 * That distinction drives most of what follows. Its lines are immutable once
 * written ({@code updatable = false} throughout {@link OrderItem}), its product
 * names are copied rather than resolved, and there is no {@code removeItem} —
 * an order that shipped the wrong thing is corrected by a return or a
 * cancellation, both of which are new facts, not by editing history so it reads
 * as though the mistake never occurred.
 * <p>
 * Identified by a {@link UUID} for the same reason a cart is: the id travels to
 * the client, and a sequential key would leak order volume and invite
 * id-walking. Guessability matters more here than for carts — {@code GET
 * /api/v1/orders/{id}} is scoped to the caller's own {@code sub}, so an
 * enumerable id would at worst reveal that an order exists, but there is no
 * reason to hand out even that.
 * <p>
 * {@code userId} is the Keycloak {@code sub} claim: a value reference to an
 * identity owned by Keycloak, not a foreign key. This schema has no users table
 * and must not grow one.
 */
@Entity
@Table(
        name = "orders",
        schema = "orders",
        indexes = {
                // GET /api/v1/orders is "this user's orders, newest first", and it is
                // the only listing this table has. Indexing the sort alongside the
                // filter lets that query be answered by an index scan instead of
                // fetching every order the user ever placed and sorting them.
                @Index(name = "ix_orders_user_id_created_at",
                        columnList = "user_id, created_at DESC")
        }
)
public class Order {

    /** Surrogate key, generated by Hibernate rather than the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Keycloak {@code sub} of the owning user.
     * <p>
     * The single field that decides whose order this is. It is only ever written
     * from the authenticated security context — never from a request body or
     * path variable — and every read is scoped by it, which is what makes
     * somebody else's order id indistinguishable from one that does not exist.
     */
    @NotBlank(message = "User id is required")
    @Column(name = "user_id", nullable = false, updatable = false)
    private String userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrderStatus status = OrderStatus.PENDING;

    /**
     * Order total in minor units.
     * <p>
     * Stored rather than derived on read, because it is part of the record: the
     * total the customer agreed to is a fact about the order, and recomputing it
     * later would let a change in how lines are summed silently restate a
     * historical figure. Kept honest by {@link #addItem(OrderItem)}, which is the
     * only way to add a line and always advances this in step — there is no path
     * that can leave the stored total disagreeing with the lines.
     */
    @PositiveOrZero(message = "Order total cannot be negative")
    @Column(name = "total_cents", nullable = false)
    private long totalCents;

    /**
     * ISO-4217 code the {@link #totalCents} figure is denominated in.
     * <p>
     * Null until the first line arrives — see {@link #addItem(OrderItem)}, which
     * adopts the currency of the line it is given. A line-less order therefore
     * fails to persist against this column's {@code NOT NULL}, which is the
     * correct outcome: checkout rejects an empty cart with a 400 long before an
     * {@code Order} is constructed, so an order with no lines reaching the
     * database at all would mean that guard had been bypassed.
     */
    @NotBlank(message = "Currency is required")
    @Size(min = 3, max = 3, message = "Currency must be a 3-letter ISO-4217 code")
    @Column(name = "currency", nullable = false, length = 3, columnDefinition = "char(3)")
    private String currency;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Last modification of this row.
     * <p>
     * Unlike a cart, an order has no {@code touch()} escape hatch: its lines are
     * write-once, so the only thing that can change after creation is the status,
     * which dirties this row directly and refreshes the column on its own.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * The order lines, owned wholly by this order.
     * <p>
     * Kept private with mutation funnelled through {@link #addItem(OrderItem)} so
     * the two sides of the association can never disagree, and so the running
     * total cannot be bypassed. {@code orphanRemoval} is present for symmetry
     * with the cascade rather than as a feature: nothing removes an order line.
     */
    @OneToMany(
            mappedBy = "order",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<OrderItem> items = new ArrayList<>();

    /** No-args constructor required by JPA. */
    protected Order() {
    }

    /**
     * Opens a new, empty {@link OrderStatus#PENDING} order for the given user.
     * <p>
     * Lines are added immediately afterwards by checkout; an {@code Order} is
     * never meant to be persisted in the state this constructor leaves it in.
     */
    public Order(String userId) {
        this.userId = userId;
        this.status = OrderStatus.PENDING;
    }

    /**
     * Appends a line, advancing the order total in the same step.
     * <p>
     * <b>Rejects a line in a different currency from the ones already present.</b>
     * Summing minor units across currencies produces a number that looks like
     * money and is not — 100 LKR plus 100 USD is not 200 of anything — and the
     * result would be stored, displayed, and eventually charged. Today every
     * price in the catalogue is LKR, so this can only fire if the data changes
     * underneath the assumption; that is exactly when a loud failure beats a
     * plausible-looking total. Splitting a mixed-currency basket into one order
     * per currency is a product decision, and this is the check that forces it to
     * be made deliberately rather than discovered in a ledger.
     *
     * @param item the line to append
     * @throws IllegalArgumentException if the line's currency differs from the
     *                                  order's
     */
    public void addItem(OrderItem item) {
        if (currency == null) {
            this.currency = item.getCurrency();
        } else if (!currency.equals(item.getCurrency())) {
            throw new IllegalArgumentException(
                    "Cannot add a " + item.getCurrency() + " line to an order denominated in "
                            + currency + " — an order carries a single currency.");
        }
        items.add(item);
        item.setOrder(this);
        this.totalCents += item.lineTotalCents();
    }

    public UUID getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public long getTotalCents() {
        return totalCents;
    }

    public String getCurrency() {
        return currency;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * The order lines, unmodifiable — append via {@link #addItem(OrderItem)}.
     * <p>
     * No setter and no remover by design; see the class note on why an order is
     * not edited after the fact.
     */
    public List<OrderItem> getItems() {
        return Collections.unmodifiableList(items);
    }
}
