package com.devicelk.productservice.service.impl;

import com.devicelk.productservice.domain.Product;
import com.devicelk.productservice.dto.ProductResponseDTO;
import com.devicelk.productservice.exception.ProductNotFoundException;
import com.devicelk.productservice.repository.ProductRepository;
import com.devicelk.productservice.service.ProductService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Default implementation of {@link ProductService}.
 * <p>
 * Holds the CRUD business logic and is responsible for mapping the
 * {@link Product} JPA entity to the {@link ProductResponseDTO} exposed by
 * the API. Constructor injection is used so the dependency is final and the
 * class stays easy to test.
 */
@Service
public class ProductServiceImpl implements ProductService {

    private final ProductRepository productRepository;

    public ProductServiceImpl(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    @Override
    @Transactional
    public ProductResponseDTO createProduct(Product product) {
        // Ensure the id is generated by the database rather than supplied by the client.
        product.setId(null);
        Product saved = productRepository.save(product);
        return mapToResponse(saved);
    }

    @Override
    @Transactional(readOnly = true)
    public List<ProductResponseDTO> getAllProducts() {
        return productRepository.findAll().stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public ProductResponseDTO getProductById(Long id) {
        Product product = productRepository.findById(id)
                .orElseThrow(() -> new ProductNotFoundException(id));
        return mapToResponse(product);
    }

    /** Maps a persisted entity to the immutable response DTO. */
    private ProductResponseDTO mapToResponse(Product product) {
        return new ProductResponseDTO(
                product.getId(),
                product.getName(),
                product.getBrand(),
                product.getCategory(),
                product.getPrice(),
                product.getStockQuantity(),
                product.getDescription()
        );
    }
}
