package com.devicelk.service.impl;

import com.devicelk.domain.Product;
import com.devicelk.dto.ProductResponseDTO;
import com.devicelk.exception.ProductNotFoundException;
import com.devicelk.repository.ProductRepository;
import com.devicelk.service.ProductService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Default implementation of {@link ProductService}.
 * <p>
 * Holds the CRUD business logic and is responsible for mapping the
 * {@link Product} JPA entity to the {@link ProductResponseDTO} exposed by
 * the API. Constructor injection is used so the dependency is final and the
 * class stays easy to test.
 */
@Service
public class ProductServiceImpl implements ProductService {

    private final ProductRepository productRepository;

    public ProductServiceImpl(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    @Override
    @Transactional
    public ProductResponseDTO createProduct(Product product) {
        // CRITICAL CHECK: Enforce uniqueness before saving to the database
        if (productRepository.existsByNameAndBrand(product.getName(), product.getBrand())) {
            throw new IllegalArgumentException(
                    "A product with the name '" + product.getName() + "' under brand '" + product.getBrand() + "' already exists in the inventory."
            );
        }

        // Mapping and saving logic (Keep your existing conversion to ProductResponseDTO here)
        Product savedProduct = productRepository.save(product);

        // Assumed conversion based on your record structure:
        return new ProductResponseDTO(
                savedProduct.getId(),
                savedProduct.getName(),
                savedProduct.getBrand(),
                savedProduct.getCategory(),
                savedProduct.getPrice(),
                savedProduct.getStockQuantity(),
                savedProduct.getDescription()
        );
        // Ensure the id is generated by the database rather than supplied by the client.
//        product.setId(null);
//        Product saved = productRepository.save(product);
//        return mapToResponse(saved);
    }

    @Override
    @Transactional(readOnly = true)
    public List<ProductResponseDTO> getAllProducts() {
        return productRepository.findAll().stream()
                .map(this::mapToResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public ProductResponseDTO getProductById(Long id) {
        Product product = productRepository.findById(id)
                .orElseThrow(() -> new ProductNotFoundException(id));
        return mapToResponse(product);
    }

    /** Maps a persisted entity to the immutable response DTO. */
    private ProductResponseDTO mapToResponse(Product product) {
        return new ProductResponseDTO(
                product.getId(),
                product.getName(),
                product.getBrand(),
                product.getCategory(),
                product.getPrice(),
                product.getStockQuantity(),
                product.getDescription()
        );
    }
}
