package com.devicelk.cart.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

/**
 * A shopping basket belonging to one user, mapped to {@code cart.carts}.
 * <p>
 * The aggregate root of the cart module: {@link CartItem}s have no life of their
 * own and are reached, added and removed only through the cart that owns them.
 * That is what {@code cascade}/{@code orphanRemoval} below encode — deleting a
 * line from {@link #items} deletes the row.
 * <p>
 * Identified by a {@link UUID} rather than a sequence: carts are created by
 * anonymous-ish user traffic and their ids travel to the client, so a
 * non-guessable, non-enumerable key avoids leaking volume and inviting
 * id-walking. The trade-off — a wider, randomly-ordered index key — is
 * irrelevant at this table's size.
 * <p>
 * {@code userId} is the Keycloak {@code sub} claim. It is a value reference to
 * an identity owned by Keycloak, not a foreign key: this schema has no users
 * table and must not grow one.
 */
@Entity
@Table(
        name = "carts",
        schema = "cart",
        indexes = {
                // Every read starts "the active cart for this user"; without this
                // the lookup degrades to a full scan as carts accumulate.
                @Index(name = "ix_carts_user_id_status", columnList = "user_id, status")
        }
)
public class Cart {

    /** Surrogate key, generated by Hibernate rather than the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Keycloak {@code sub} of the owning user.
     * <p>
     * The single field that decides whose cart this is. It is only ever written
     * from the authenticated security context — never from a request body or
     * path variable, which would let a caller name someone else's cart.
     */
    @NotBlank(message = "User id is required")
    @Column(name = "user_id", nullable = false)
    private String userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private CartStatus status = CartStatus.ACTIVE;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Last modification of <b>this row</b>.
     * <p>
     * Hibernate refreshes it when the cart itself is dirty; a change confined to
     * a child row does not qualify. The service layer therefore touches the cart
     * explicitly on item changes — see {@link #touch()} — so the column means
     * "cart last changed" rather than the much narrower "cart header last
     * changed", which is what a caller reading it will assume.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * The basket lines, owned wholly by this cart.
     * <p>
     * Kept private with mutation funnelled through {@link #addItem(CartItem)} and
     * {@link #removeItem(CartItem)} so the two sides of the association can never
     * disagree — an item added to this list without its {@code cart} back-pointer
     * set would fail to insert on flush.
     */
    @OneToMany(
            mappedBy = "cart",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<CartItem> items = new ArrayList<>();

    /** No-args constructor required by JPA. */
    protected Cart() {
    }

    /** Opens a new, empty, {@link CartStatus#ACTIVE} cart for the given user. */
    public Cart(String userId) {
        this.userId = userId;
        this.status = CartStatus.ACTIVE;
    }

    /** Links an item to this cart, keeping both ends of the association in step. */
    public void addItem(CartItem item) {
        items.add(item);
        item.setCart(this);
    }

    /** Detaches an item; {@code orphanRemoval} turns this into a DELETE on flush. */
    public void removeItem(CartItem item) {
        items.remove(item);
        item.setCart(null);
    }

    /** Empties the basket, deleting every line on flush. */
    public void clearItems() {
        items.forEach(item -> item.setCart(null));
        items.clear();
    }

    /**
     * Marks this cart as converted into an order.
     *
     * @throws IllegalStateException if the cart is not currently
     *         {@link CartStatus#ACTIVE} — checking out a cart twice would let two
     *         orders claim one basket
     */
    public void markCheckedOut() {
        if (status != CartStatus.ACTIVE) {
            throw new IllegalStateException(
                    "Cart " + id + " cannot be checked out from status " + status);
        }
        this.status = CartStatus.CHECKED_OUT;
    }

    /**
     * Forces {@link #updatedAt} to advance when only a child row changed.
     * <p>
     * Assigning the field marks the entity dirty, so Hibernate issues an UPDATE
     * and {@code @UpdateTimestamp} overwrites this placeholder with the flush
     * time. The value written here is never the one that lands in the column.
     */
    public void touch() {
        this.updatedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public CartStatus getStatus() {
        return status;
    }

    public void setStatus(CartStatus status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /** The basket lines, unmodifiable — mutate via {@link #addItem(CartItem)} and friends. */
    public List<CartItem> getItems() {
        return Collections.unmodifiableList(items);
    }
}
