package com.devicelk.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

/**
 * JPA entity representing a single product held in the DeviceLK inventory.
 * <p>
 * This is the <b>Domain/Model</b> layer. The class is mapped to the
 * {@code products} table; Hibernate generates the schema automatically
 * (see {@code spring.jpa.hibernate.ddl-auto}).
 */
@Entity
@Table(
        name = "products",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uc_product_name_brand",
                        columnNames = {"name", "brand"}
                )
        }
)
public class Product {

    /** Surrogate primary key, generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Product name is required")
    @Column(nullable = false)
    private String name;

    @NotBlank(message = "Brand is required")
    @Column(nullable = false)
    private String brand;

    /**
     * Stored as its {@code String} name (e.g. "LAPTOP") rather than its ordinal,
     * keeping the column human-readable and resilient to enum reordering.
     */
    @NotNull(message = "Category is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private Category category;

    @NotNull(message = "Price is required")
    @Positive(message = "Price must be greater than zero")
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity cannot be negative")
    @Column(nullable = false)
    private Integer stockQuantity;

    /**
     * Re-order trigger level. When {@code stockQuantity} drops to or below this
     * value, the service layer raises a low-stock alert (see
     * {@code ProductServiceImpl#adjustStock}).
     */
    @NotNull(message = "Minimum stock threshold is required")
    @Min(value = 0, message = "Minimum stock threshold cannot be negative")
    @Column(nullable = false)
    private Integer minStockThreshold;

    @Size(max = 1000, message = "Description cannot exceed 1000 characters")
    @Column(length = 1000)
    private String description;

    /** No-args constructor required by JPA. */
    public Product() {
    }

    /** Convenience constructor for creating a new (unpersisted) product. */
    public Product(String name,
                   String brand,
                   Category category,
                   BigDecimal price,
                   Integer stockQuantity,
                   Integer minStockThreshold,
                   String description) {
        this.name = name;
        this.brand = brand;
        this.category = category;
        this.price = price;
        this.stockQuantity = stockQuantity;
        this.minStockThreshold = minStockThreshold;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getStockQuantity() {
        return stockQuantity;
    }

    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    public Integer getMinStockThreshold() {
        return minStockThreshold;
    }

    public void setMinStockThreshold(Integer minStockThreshold) {
        this.minStockThreshold = minStockThreshold;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
